### ISSUE TITLE
Tree shaking error

### ISSUE THREAD

**Issue by brim-borium** [TunNandaAung/heroicons_flutter#2]
Hello first of all thanks for the package :)

I am currently getting the following error regarding tree shaking when doing a release build on Flutter 3.10.5 on Android and iOS:

```
This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - ..heroicons_flutter-0.2.3/lib/heroicons_flutter.dart:656:12
Target aot_android_asset_bundle failed: Exception: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.
```

Is this something you can fix on your end? Or do I have to used the proposed solution? Seems to me that you just have to add a const value in the proposed line :)

**Comment by TunNandaAung** [comment]
Thanks for reporting the issue. 
This problem occurs when `fromString` method is used because it has to go through the list of icons to find the one that matches the given string. As a result, this cannot be marked as `const` and tree shaking won’t work. So, if you want to use `fromString`, you can use the proposed solution by adding the `—no-tree-shake-icons` flag.
I will add a note about this in the next release.

**Comment by TunNandaAung** [comment]
Add a note on `fromString()` and tree shaking in [v0.3.0](https://github.com/TunNandaAung/heroicons_flutter/releases/tag/v0.3.0) (3a41cad928f2ebff0b713439e8d13650b11821f4)

**Comment by danialb007** [comment]
Just came across the same problem and im not using `fromString` method
